version: "1"
projects:
- name: MemoryMeet
  environments:
  - name: Production
    services:
    - type: web
      name: MemoryMeet
      runtime: python
      repo: https://github.com/shaswat-shukla-dev/MemoryMeet
      plan: free
      region: singapore
      rootDir: backend
      buildCommand: pip install -r requirements.txt
      startCommand: "gunicorn app:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
      autoDeployTrigger: commit
      envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HINDSIGHT_API_KEY
        sync: false
      - key: HINDSIGHT_BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false